In [3]:
import numpy as np


In [49]:
a=np.random.rand(2,2)
print(a)

[[ 0.10256458  0.29624966]
 [ 0.56256683  0.22075193]]


In [6]:
b=np.random.rand(2,2,4,4)

In [7]:
c=np.random.rand(4,4,2,2)

In [10]:
np.einsum('ijkl,klnm->ijnm', b,c).shape

(2, 2, 2, 2)

In [48]:
d=np.random.rand(2)
print(d)

[ 0.64414547  0.36555346]


In [50]:
np.einsum('ij,i->j',a,d)

array([ 0.27171476,  0.27152451])

In [51]:
np.einsum('ij,j->i',a,d)

array([ 0.1743616,  0.4430715])

In [52]:
np.dot(a,d)

array([ 0.1743616,  0.4430715])

In [53]:
np.dot(d,a)

array([ 0.27171476,  0.27152451])

In [ ]:
# Need to see if I can add 0's i.e arbitarily increase bond dimension but setting new values to zero

# Need to see if  I can add 0,1's i.e arbitrarily add |0>'s 
#> essentially, adding an extra bondwith new values set to zero

# Need to see if I can reshape to matrix and back without spoiling it (CHECKED AND SO FAR SO GOOD)

#quickly remind myself how to project an input into a bond

In [30]:
c2=np.reshape(c, (16,4))

In [31]:
c2

array([[ 0.26017183,  0.7939583 ,  0.68200133,  0.93872591],
       [ 0.93173492,  0.73282937,  0.90001583,  0.76625567],
       [ 0.56865303,  0.31425692,  0.13653002,  0.18542811],
       [ 0.42116737,  0.69449337,  0.4931706 ,  0.9424484 ],
       [ 0.57472368,  0.46645045,  0.08819809,  0.49030106],
       [ 0.1068114 ,  0.04203312,  0.54282563,  0.62833359],
       [ 0.3040157 ,  0.72416223,  0.75454315,  0.95724481],
       [ 0.51268142,  0.6701093 ,  0.92069657,  0.68876391],
       [ 0.41726396,  0.91282489,  0.57627087,  0.35157166],
       [ 0.50777429,  0.41069516,  0.54202005,  0.21178431],
       [ 0.21279806,  0.22356335,  0.49029219,  0.85787973],
       [ 0.65431171,  0.39795031,  0.06854638,  0.41133147],
       [ 0.46751176,  0.15394514,  0.90748024,  0.12438396],
       [ 0.84284019,  0.28930519,  0.22913674,  0.8274231 ],
       [ 0.39707134,  0.52012935,  0.92947927,  0.89877522],
       [ 0.73786989,  0.19125946,  0.4818155 ,  0.52572125]])

In [35]:
c3=np.reshape(c,(4,4,2,2))
c3=c3+1

In [36]:
c3-c

array([[[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]],


       [[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]],


       [[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]],


       [[[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]],

        [[ 1.,  1.],
         [ 1.,  1.]]]])